config/routes.rb
Questions::Application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: [:index, :create]
  resources :votes, only: [:create]
  resource :session, only: [:create]

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :votes

  validates :body, :user_id, presence: true

  default_scope order('votes_count DESC')

  def self.todays_questions
    Question.all.map { |question| question.formatted_json }
    # Question.where('created_at > ')
  end

  def vote_count
    votes_count
  end

  def formatted_json
    { body: body, author: author.name, votes: votes.count, id: id }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :fname, :lname

  has_many :questions
  has_many :votes
  has_many :upvoted_questions, through: :votes

  validates :email, :fname, :lname, presence: true

  def to_s
    name
  end

  def name
    "#{fname} #{lname}"
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :question_id, :user_id

  belongs_to :user
  belongs_to :upvoted_question, class_name: 'Question',
             foreign_key: :question_id, counter_cache: true

  validates :question_id, :user_id, presence: true
  validates :question_id, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # before_filter :check_logged_in

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def check_logged_in
    unless logged_in?
      render json: { errors: 'Must be logged in' }, status: :forbidden
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @users = User.all
    @question = Question.new
    @questions = Question.todays_questions

    respond_to do |format|
      format.html
      format.json { render :json => @questions }
    end
  end

  def create
    @question = current_user.questions.new(params[:question])

    if @question.save
      render json: @question.formatted_json
    else
      render nothing: true, status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find(params[:session][:user_id])
    login(@user)

    render nothing: true, status: :ok
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.new(question_id: params[:question_id])
    @question = Question.find(params[:question_id])

    if @vote.save
      render json: @question
    else
      render nothing: true, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'shared/menu' %>

  <%= yield %>

  <%= javascript_include_tag "application" %>
  <script>
    $(function() {
      $('.login-dropdown select').select2({
        placeholder: 'Login Here',
        allowClear: true
      });
    })
  </script>
  <link href='http://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'>
</body>
</html>

app/views/questions/_question.html.erb
<div class="question">
  <div class="vote-button">
    <a href="#">
      <%= form_tag votes_path, remote: true do %>
        <%= hidden_field_tag :question_id, question.id %>
        <%= submit_tag 'Upvote', class: 'upvote-button' %>
      <% end %>
    </a>
  </div>

  <div class="vote-count">
    <%= question.vote_count %>
  </div>

  <div class="question-show">
    <div class="question-body">
      <%= question.body %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="wrapper">
  <h2 class="bigheader">Ask</h2>
  <div class="container">
    <div class="login">
      Current Student:
      <%= form_tag session_path, remote: true, class: 'login-dropdown' do %>
        <%= collection_select :session, :user_id, @users, :id, :name %>
        <%= submit_tag 'Login' %>
      <% end %>
    </div>

    <%= form_for @question, remote: true, id: "new_question" do |f| %>
      <%= f.text_area :body %>
      <%= f.submit 'Ask' %>
    <% end %>

    <h2>Questions</h2>
    <div class="questions">
    </div>

    <script id="question-tpl" type="text/x-handlebars-template">
      <div data-question-id="{{id}}" class="question">
        <p>{{body}}</p>
        <div class="author">{{author}}</div>
        <div class="vote-count">{{votes}}</div>
        <button type="button" class="vote">Awesome</button>
      </div>
    </script>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1>
        <a href="/">Q&A</a>
      </h1>
    </li>
  </ul>

  <ul class="right">
    <li class="login">

    </li>
  </ul>
</nav>